import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const GATEWAY_URL = "https://connector-gateway.lovable.dev/resend";

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { persistSession: false } }
  );

  try {
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY_1");
    if (!RESEND_API_KEY) throw new Error("RESEND_API_KEY_1 not configured");

    // Authenticate the caller
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("Not authenticated");
    const token = authHeader.replace("Bearer ", "");
    const { data: { user } } = await supabase.auth.getUser(token);
    if (!user) throw new Error("Not authenticated");

    // Check caller is manager or owner
    const { data: roles } = await supabase
      .from("user_roles")
      .select("role")
      .eq("user_id", user.id);
    const userRoles = (roles || []).map((r: any) => r.role);
    if (!userRoles.includes("owner") && !userRoles.includes("manager")) {
      throw new Error("Not authorized");
    }

    const { scorecard, sender_name } = await req.json();
    if (!scorecard || !Array.isArray(scorecard)) {
      throw new Error("Invalid scorecard data");
    }

    const today = new Date().toLocaleDateString("en-US", {
      timeZone: "America/New_York",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    // Build HTML table
    const tableRows = scorecard.map((row: any) => {
      const overdueColor = row.followUpsOverdue === 0 ? "#22c55e" : row.followUpsOverdue <= 3 ? "#f59e0b" : "#ef4444";
      return `<tr>
        <td style="padding:8px 12px;border:1px solid #e5e7eb;">${row.name}</td>
        <td style="padding:8px 12px;border:1px solid #e5e7eb;text-align:center;">${row.leadsAssigned}</td>
        <td style="padding:8px 12px;border:1px solid #e5e7eb;text-align:center;">${row.leadsContactedThisWeek}</td>
        <td style="padding:8px 12px;border:1px solid #e5e7eb;text-align:center;color:${overdueColor};font-weight:bold;">${row.followUpsOverdue}</td>
        <td style="padding:8px 12px;border:1px solid #e5e7eb;text-align:center;">${row.stageMovementsThisWeek}</td>
        <td style="padding:8px 12px;border:1px solid #e5e7eb;text-align:center;">$${row.commissionsThisMonth.toFixed(2)}</td>
      </tr>`;
    }).join("");

    const html = `
    <div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px;">
      <h1 style="color:#1a1a2e;font-size:22px;">Weekly Accountability Report</h1>
      <p style="color:#666;font-size:14px;">A-Z Enterprises — ${today}</p>
      <p style="color:#666;font-size:14px;">Generated by ${sender_name || "Victoria Jackson"}</p>
      <table style="width:100%;border-collapse:collapse;margin:20px 0;font-size:14px;">
        <thead>
          <tr style="background:#1a1a2e;color:#fff;">
            <th style="padding:10px 12px;text-align:left;">Team Member</th>
            <th style="padding:10px 12px;text-align:center;">Leads Assigned</th>
            <th style="padding:10px 12px;text-align:center;">Contacted This Week</th>
            <th style="padding:10px 12px;text-align:center;">Follow-Ups Overdue</th>
            <th style="padding:10px 12px;text-align:center;">Stage Movements</th>
            <th style="padding:10px 12px;text-align:center;">Commissions MTD</th>
          </tr>
        </thead>
        <tbody>${tableRows}</tbody>
      </table>
      <p style="color:#999;font-size:12px;margin-top:20px;">This report was generated from A-Z Command Platform.</p>
    </div>`;

    const response = await fetch(`${GATEWAY_URL}/emails`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${LOVABLE_API_KEY}`,
        "X-Connection-Api-Key": RESEND_API_KEY,
      },
      body: JSON.stringify({
        from: "A-Z Command <victoria@azenterpriseshq.com>",
        to: ["dylan@a-zenterpriseshq.com"],
        subject: `Weekly Accountability Report — A-Z Enterprises — ${today}`,
        html,
      }),
    });

    const result = await response.json();
    if (!response.ok) {
      throw new Error(`Resend API error [${response.status}]: ${JSON.stringify(result)}`);
    }

    console.log("[ACCOUNTABILITY-REPORT] Email sent successfully", result);

    return new Response(JSON.stringify({ success: true }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 200,
    });
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error("[ACCOUNTABILITY-REPORT] ERROR:", msg);

    // Log to edge_function_errors
    try {
      await supabase.from("edge_function_errors").insert({
        function_name: "send-accountability-report",
        error_message: msg,
        stack_trace: error instanceof Error ? error.stack : null,
        payload: {},
      });
    } catch (_) {}

    return new Response(JSON.stringify({ error: msg }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 500,
    });
  }
});
