import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Calendar } from "@/components/ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { toast } from "sonner";
import { format, addDays } from "date-fns";
import { CalendarDays, Users, Clock, DollarSign } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { useBusinessByType } from "@/hooks/useBusinesses";
import { useBookableTypes } from "@/hooks/useBookableTypes";
import { usePackages } from "@/hooks/usePackages";
import { useCreateBooking } from "@/hooks/useBookings";
import { supabase } from "@/integrations/supabase/client";
import { cn } from "@/lib/utils";

interface EventRequestFormProps {
  onSuccess?: (bookingId: string) => void;
}

export default function EventRequestForm({ onSuccess }: EventRequestFormProps) {
  const navigate = useNavigate();
  const { user, authUser } = useAuth();
  const { data: business } = useBusinessByType("summit");
  const { data: bookableTypes } = useBookableTypes(business?.id);
  const [selectedTypeId, setSelectedTypeId] = useState<string>("");
  const { data: packages } = usePackages(selectedTypeId);
  const createBooking = useCreateBooking();

  const [formData, setFormData] = useState({
    eventType: "",
    startDate: undefined as Date | undefined,
    endDate: undefined as Date | undefined,
    guestCount: "",
    notes: "",
    guestName: "",
    guestEmail: "",
    guestPhone: "",
    packageId: "",
  });

  const [isSubmitting, setIsSubmitting] = useState(false);

  const selectedPackage = packages?.find(p => p.id === formData.packageId);
  const selectedType = bookableTypes?.find(t => t.id === selectedTypeId);

  const calculateTotal = () => {
    if (!selectedPackage) return 0;
    return selectedPackage.base_price;
  };

  const calculateDeposit = () => {
    const total = calculateTotal();
    if (selectedType?.deposit_percentage) {
      return Math.round(total * (selectedType.deposit_percentage / 100));
    }
    if (selectedType?.deposit_fixed_amount) {
      return selectedType.deposit_fixed_amount;
    }
    return Math.round(total * 0.25); // Default 25%
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!business || !selectedTypeId || !formData.startDate) {
      toast.error("Please fill in all required fields");
      return;
    }

    if (!user && (!formData.guestEmail || !formData.guestName)) {
      toast.error("Please provide your contact information");
      return;
    }

    setIsSubmitting(true);

    try {
      const endDate = formData.endDate || formData.startDate;
      const total = calculateTotal();
      const deposit = calculateDeposit();

      const bookingData = {
        business_id: business.id,
        bookable_type_id: selectedTypeId,
        package_id: formData.packageId || null,
        customer_id: user?.id || null,
        guest_name: formData.guestName || null,
        guest_email: formData.guestEmail || null,
        guest_phone: formData.guestPhone || null,
        guest_count: parseInt(formData.guestCount) || null,
        start_datetime: formData.startDate.toISOString(),
        end_datetime: endDate.toISOString(),
        notes: formData.notes,
        status: "pending" as const,
        subtotal: total,
        total_amount: total,
        deposit_amount: deposit,
        balance_due: total - deposit,
        balance_due_date: addDays(formData.startDate, -14).toISOString(),
        booking_number: "", // Will be generated by trigger
      };

      const result = await createBooking.mutateAsync(bookingData);

      // Log to audit
      await supabase.from("audit_log").insert([{
        entity_type: "booking",
        entity_id: result.id,
        action_type: "event_request_submitted",
        after_json: { event_type: formData.eventType, guest_count: formData.guestCount } as any,
      }]);

      toast.success("Event request submitted! We'll review and respond within 24-48 hours.");
      onSuccess?.(result.id);
      navigate(`/booking/confirmation?id=${result.id}&pending=true`);
    } catch (error) {
      toast.error("Failed to submit request. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <CalendarDays className="h-5 w-5" />
            Event Details
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Event Type *</Label>
              <Select 
                value={selectedTypeId} 
                onValueChange={(v) => {
                  setSelectedTypeId(v);
                  setFormData(prev => ({ ...prev, packageId: "" }));
                }}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select event type" />
                </SelectTrigger>
                <SelectContent>
                  {bookableTypes?.map((type) => (
                    <SelectItem key={type.id} value={type.id}>
                      {type.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Expected Guests *</Label>
              <div className="relative">
                <Users className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  type="number"
                  placeholder="Number of guests"
                  value={formData.guestCount}
                  onChange={(e) => setFormData(prev => ({ ...prev, guestCount: e.target.value }))}
                  className="pl-10"
                  min={selectedType?.min_guests || 1}
                  max={selectedType?.max_guests || 500}
                />
              </div>
              {selectedType?.max_guests && (
                <p className="text-xs text-muted-foreground">Max capacity: {selectedType.max_guests}</p>
              )}
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Event Date *</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" className={cn("w-full justify-start text-left", !formData.startDate && "text-muted-foreground")}>
                    <CalendarDays className="mr-2 h-4 w-4" />
                    {formData.startDate ? format(formData.startDate, "PPP") : "Select date"}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0">
                  <Calendar
                    mode="single"
                    selected={formData.startDate}
                    onSelect={(date) => setFormData(prev => ({ ...prev, startDate: date }))}
                    disabled={(date) => date < new Date()}
                  />
                </PopoverContent>
              </Popover>
            </div>

            <div className="space-y-2">
              <Label>End Date (for multi-day events)</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" className={cn("w-full justify-start text-left", !formData.endDate && "text-muted-foreground")}>
                    <CalendarDays className="mr-2 h-4 w-4" />
                    {formData.endDate ? format(formData.endDate, "PPP") : "Same day"}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0">
                  <Calendar
                    mode="single"
                    selected={formData.endDate}
                    onSelect={(date) => setFormData(prev => ({ ...prev, endDate: date }))}
                    disabled={(date) => date < (formData.startDate || new Date())}
                  />
                </PopoverContent>
              </Popover>
            </div>
          </div>
        </CardContent>
      </Card>

      {selectedTypeId && packages && packages.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Select Package</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-4">
              {packages.map((pkg) => (
                <Card 
                  key={pkg.id}
                  className={cn(
                    "cursor-pointer transition-all hover:border-primary",
                    formData.packageId === pkg.id && "border-primary ring-2 ring-primary"
                  )}
                  onClick={() => setFormData(prev => ({ ...prev, packageId: pkg.id }))}
                >
                  <CardContent className="p-4">
                    <div className="flex justify-between items-start">
                      <div>
                        <h4 className="font-semibold">{pkg.name}</h4>
                        <p className="text-sm text-muted-foreground">{pkg.description}</p>
                        <div className="flex items-center gap-2 mt-2 text-sm">
                          <Clock className="h-4 w-4" />
                          <span>{pkg.duration_mins} minutes</span>
                        </div>
                      </div>
                      <div className="text-right">
                        <p className="text-lg font-bold">${pkg.base_price.toLocaleString()}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {!user && (
        <Card>
          <CardHeader>
            <CardTitle>Contact Information</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Your Name *</Label>
                <Input
                  value={formData.guestName}
                  onChange={(e) => setFormData(prev => ({ ...prev, guestName: e.target.value }))}
                  placeholder="Full name"
                  required={!user}
                />
              </div>
              <div className="space-y-2">
                <Label>Email *</Label>
                <Input
                  type="email"
                  value={formData.guestEmail}
                  onChange={(e) => setFormData(prev => ({ ...prev, guestEmail: e.target.value }))}
                  placeholder="your@email.com"
                  required={!user}
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label>Phone</Label>
              <Input
                type="tel"
                value={formData.guestPhone}
                onChange={(e) => setFormData(prev => ({ ...prev, guestPhone: e.target.value }))}
                placeholder="(555) 123-4567"
              />
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Additional Notes</CardTitle>
        </CardHeader>
        <CardContent>
          <Textarea
            placeholder="Tell us about your vision for the event, special requirements, dietary needs, etc."
            value={formData.notes}
            onChange={(e) => setFormData(prev => ({ ...prev, notes: e.target.value }))}
            rows={4}
          />
        </CardContent>
      </Card>

      {selectedPackage && (
        <Card className="bg-muted/30">
          <CardContent className="p-6">
            <div className="flex justify-between items-center">
              <div>
                <p className="text-sm text-muted-foreground">Estimated Total</p>
                <p className="text-2xl font-bold">${calculateTotal().toLocaleString()}</p>
              </div>
              <div className="text-right">
                <p className="text-sm text-muted-foreground">Deposit Required</p>
                <p className="text-lg font-semibold text-primary">${calculateDeposit().toLocaleString()}</p>
                <p className="text-xs text-muted-foreground">Due upon approval</p>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      <Button type="submit" size="lg" className="w-full" disabled={isSubmitting || !selectedTypeId || !formData.startDate}>
        {isSubmitting ? "Submitting..." : "Submit Event Request"}
      </Button>

      <p className="text-sm text-muted-foreground text-center">
        Our team will review your request and respond within 24-48 hours. A deposit will be required upon approval.
      </p>
    </form>
  );
}
