import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.2";
import { PDFDocument, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { persistSession: false } }
  );

  try {
    const { payroll_run_id } = await req.json();
    if (!payroll_run_id) {
      return new Response(JSON.stringify({ error: "payroll_run_id required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Fetch payroll run
    const { data: run, error: runErr } = await supabase
      .from("payroll_runs")
      .select("*")
      .eq("id", payroll_run_id)
      .single();
    if (runErr || !run) throw new Error("Payroll run not found");

    // Fetch commissions with employee info
    const { data: commissions } = await supabase
      .from("crm_commissions")
      .select(`
        id, amount, status,
        employee:profiles!crm_commissions_employee_id_fkey(first_name, last_name),
        revenue_event:crm_revenue_events!crm_commissions_revenue_event_id_fkey(description, business_unit)
      `)
      .eq("payroll_run_id", payroll_run_id);

    // Group by employee
    const employeeGroups: Record<string, { name: string; items: { type: string; description: string; amount: number }[] }> = {};
    for (const c of (commissions || [])) {
      const emp = c.employee as any;
      const name = `${emp?.first_name || ""} ${emp?.last_name || ""}`.trim() || "Unknown";
      if (!employeeGroups[name]) {
        employeeGroups[name] = { name, items: [] };
      }
      const rev = c.revenue_event as any;
      employeeGroups[name].items.push({
        type: "Commission",
        description: rev?.description || `${rev?.business_unit || "General"} commission`,
        amount: Number(c.amount),
      });
    }

    // Build PDF
    const pdfDoc = await PDFDocument.create();
    const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const PAGE_WIDTH = 612;
    const PAGE_HEIGHT = 792;
    const MARGIN = 50;
    const LINE_HEIGHT = 16;
    let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    let y = PAGE_HEIGHT - MARGIN;

    const addNewPageIfNeeded = (needed: number) => {
      if (y - needed < MARGIN + 40) {
        page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
        y = PAGE_HEIGHT - MARGIN;
      }
    };

    const drawText = (text: string, x: number, yPos: number, font = helvetica, size = 10, color = rgb(0.2, 0.2, 0.2)) => {
      page.drawText(text, { x, y: yPos, size, font, color });
    };

    // Header
    drawText("A-Z Enterprises", MARGIN, y, helveticaBold, 22, rgb(0, 0, 0));
    y -= 28;
    drawText("Payroll Summary", MARGIN, y, helveticaBold, 14, rgb(0.3, 0.3, 0.3));
    y -= 24;

    // Divider line
    page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_WIDTH - MARGIN, y }, thickness: 1, color: rgb(0.7, 0.7, 0.7) });
    y -= 24;

    // Pay period info
    const formatDate = (d: string) => {
      const dt = new Date(d + "T12:00:00");
      return dt.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
    };
    const now = new Date();
    const genTimestamp = now.toLocaleString("en-US", { month: "long", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit", hour12: true });

    drawText(`Pay Period: ${formatDate(run.period_start)} to ${formatDate(run.period_end)}`, MARGIN, y);
    y -= LINE_HEIGHT;
    drawText(`Run Date: ${formatDate(run.paid_at?.split("T")[0] || now.toISOString().split("T")[0])}`, MARGIN, y);
    y -= LINE_HEIGHT;
    drawText("Generated By: Dylan Legge", MARGIN, y);
    y -= LINE_HEIGHT;
    drawText(`Generated At: ${genTimestamp}`, MARGIN, y);
    y -= 30;

    // Table header
    const COL_NAME = MARGIN;
    const COL_TYPE = 200;
    const COL_DESC = 290;
    const COL_AMT = PAGE_WIDTH - MARGIN - 60;

    const drawTableHeader = () => {
      addNewPageIfNeeded(20);
      page.drawRectangle({ x: MARGIN, y: y - 4, width: PAGE_WIDTH - 2 * MARGIN, height: 18, color: rgb(0.93, 0.93, 0.93) });
      drawText("Employee Name", COL_NAME + 4, y, helveticaBold, 9, rgb(0.3, 0.3, 0.3));
      drawText("Item Type", COL_TYPE, y, helveticaBold, 9, rgb(0.3, 0.3, 0.3));
      drawText("Description", COL_DESC, y, helveticaBold, 9, rgb(0.3, 0.3, 0.3));
      drawText("Amount", COL_AMT, y, helveticaBold, 9, rgb(0.3, 0.3, 0.3));
      y -= 20;
    };

    drawTableHeader();

    let totalCommissions = 0;
    let totalBasePay = 0;

    const fmtMoney = (n: number) => `$${n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

    const sortedEmployees = Object.values(employeeGroups).sort((a, b) => a.name.localeCompare(b.name));

    for (const group of sortedEmployees) {
      addNewPageIfNeeded(LINE_HEIGHT * (group.items.length + 2));
      let subtotal = 0;

      for (let i = 0; i < group.items.length; i++) {
        const item = group.items[i];
        const showName = i === 0;
        if (showName) {
          drawText(group.name, COL_NAME + 4, y, helveticaBold, 9);
        }
        drawText(item.type, COL_TYPE, y, helvetica, 9);

        // Truncate description to fit
        let desc = item.description;
        if (desc.length > 35) desc = desc.substring(0, 32) + "...";
        drawText(desc, COL_DESC, y, helvetica, 9);
        drawText(fmtMoney(item.amount), COL_AMT, y, helvetica, 9);

        subtotal += item.amount;
        if (item.type === "Commission") totalCommissions += item.amount;
        else totalBasePay += item.amount;

        y -= LINE_HEIGHT;
      }

      // Subtotal row
      page.drawLine({ start: { x: COL_AMT - 10, y: y + 4 }, end: { x: PAGE_WIDTH - MARGIN, y: y + 4 }, thickness: 0.5, color: rgb(0.7, 0.7, 0.7) });
      drawText("Subtotal", COL_DESC, y, helveticaBold, 9, rgb(0.4, 0.4, 0.4));
      drawText(fmtMoney(subtotal), COL_AMT, y, helveticaBold, 9);
      y -= LINE_HEIGHT + 8;
    }

    // Summary section
    addNewPageIfNeeded(80);
    y -= 10;
    page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_WIDTH - MARGIN, y }, thickness: 1, color: rgb(0.7, 0.7, 0.7) });
    y -= 20;

    drawText("Total Commissions:", COL_DESC, y, helveticaBold, 11);
    drawText(fmtMoney(totalCommissions), COL_AMT, y, helveticaBold, 11);
    y -= LINE_HEIGHT + 2;

    drawText("Total Base Pay:", COL_DESC, y, helveticaBold, 11);
    drawText(fmtMoney(totalBasePay), COL_AMT, y, helveticaBold, 11);
    y -= LINE_HEIGHT + 2;

    const grandTotal = totalCommissions + totalBasePay;
    page.drawLine({ start: { x: COL_AMT - 10, y: y + 4 }, end: { x: PAGE_WIDTH - MARGIN, y: y + 4 }, thickness: 1, color: rgb(0, 0, 0) });
    drawText("Grand Total:", COL_DESC, y, helveticaBold, 13, rgb(0, 0, 0));
    drawText(fmtMoney(grandTotal), COL_AMT, y, helveticaBold, 13, rgb(0, 0, 0));
    y -= 40;

    // Footer
    addNewPageIfNeeded(20);
    drawText("This document was generated by A-Z Command — A-Z Enterprises — Confidential", MARGIN, MARGIN + 10, helvetica, 8, rgb(0.5, 0.5, 0.5));

    const pdfBytes = await pdfDoc.save();

    // Upload to storage
    const fileName = `payroll-${payroll_run_id}-${run.period_start}-${run.period_end}.pdf`;

    const { error: uploadError } = await supabase.storage
      .from("payroll-pdfs")
      .upload(fileName, pdfBytes, {
        contentType: "application/pdf",
        upsert: true,
      });

    if (uploadError) throw new Error(`Upload failed: ${uploadError.message}`);

    // Get public URL
    const { data: urlData } = supabase.storage.from("payroll-pdfs").getPublicUrl(fileName);
    const pdfUrl = urlData.publicUrl;

    // Update payroll run with pdf_url
    await supabase.from("payroll_runs").update({ pdf_url: pdfUrl } as any).eq("id", payroll_run_id);

    return new Response(JSON.stringify({ success: true, pdf_url: pdfUrl }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 200,
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return new Response(JSON.stringify({ error: String(error) }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 500,
    });
  }
});
